OpenSourcePolicyCenter/PolicyBrain

templates/pages/about.html
templates/pages/home.html
templates/pages/home_content.html
templates/register/post-signup-register.html
templates/register/register_success.html
webapp/apps/pages/views.py
webapp/apps/register/forms.py
webapp/apps/register/models.py
webapp/apps/register/views.py
webapp/apps/taxbrain/helpers.py

- Makes current with commit 253f05a604c02727db6d8952943c0f60e9049e44

Catch up commit from old repo.

---

templates/taxbrain/includes/params/inputs/amt.html

dividents -> dividends

---

templates/taxbrain/results.html
webapp/apps/taxbrain/helpers.py

Replace lorum

---

static/js/site.js
templates/taxbrain/includes/params/inputs/behavior.html
templates/taxbrain/includes/params/inputs/growth.html
templates/taxbrain/includes/params/inputs/itemize_ded.html
templates/taxbrain/includes/params/inputs/paramradio.html
templates/taxbrain/input_form.html
webapp/apps/taxbrain/forms.py
webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/migrations/0005_auto_20151014_2058.py
webapp/apps/taxbrain/migrations/0005_outputurl_model_pk.py
webapp/apps/taxbrain/migrations/0006_auto_20151014_1211.py
webapp/apps/taxbrain/migrations/0007_merge.py
webapp/apps/taxbrain/migrations/0008_auto_20151014_2303.py
webapp/apps/taxbrain/migrations/0009_auto_20151015_0340.py
webapp/apps/taxbrain/migrations/0010_auto_20151016_0302.py
webapp/apps/taxbrain/models.py
webapp/apps/taxbrain/views.py

Quite a bit here:
- #59 from @mistakevin 
- Enable some Behavior Effects
- Adds Growth Assumptions input features.
- also includes commits for #63

Kevin additions

---

webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/views.py

Allows a user to use TaxBrain without being logged in.

Remove permission

---

webapp/apps/taxbrain/helpers.py

Checked items in #62 are included in this PR. Everything is in line with [this PR](https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/392) to taxcalc.

Changed table headers and added payroll column

---

static/js/taxbrain.js
staticfiles/js/taxbrain.js

Fixes JS error mentioned in  #70

fix taxbrain form scroll hijacking clicks

---

templates/taxbrain/results.html
webapp/apps/taxbrain/helpers.py

- Adds 4 new tables {Payroll tax, combined tax} x {income decile, income
bin}.

Add new Payroll, Combined tables

---

webapp/apps/taxbrain/migrations/0012_taxsaveinputs_first_year.py

Forgot to add this migration when the first_year field was added to TaxSaveInputs model.

Add forgotten migration file for new model field

---

templates/pages/about.html

https://github.com/OpenSourcePolicyCenter/webapp-public/issues/56

Commented out the "What people are saying" section

---

static/js/site.js
static/js/taxbrain.js
staticfiles/js/site.js
staticfiles/js/taxbrain.js
templates/taxbrain/includes/params/inputs/paramradio.html

resolves https://github.com/OpenSourcePolicyCenter/webapp-public/issues/90

Text inputs clearing when unfocused

---

conda-requirements.txt
static/css/taxbrain.css
staticfiles/css/taxbrain.css
templates/taxbrain/includes/params/inputs/itemize_ded.html
webapp/apps/taxbrain/models.py
webapp/apps/taxbrain/views.py

- Adds additional flag for _ID_RealEstate_HC switch
- modify CSS to fit new checkbox in one line
- modify 'fixup' to properly transfer flag to dropq
resolves #106

Real estate deduction haircut

---

templates/pages/about.html

Removed the text, leaving just the AEI logo.

---

static/css/site.css
static/css/taxbrain.css
static/less/pages/home.less
staticfiles/css/site.css
staticfiles/css/taxbrain.css
staticfiles/less/pages/home.less

Compiling from less this time used 3-character representations of repeated hex colors instead of 6-character, which makes up the majority of changes in this PR. I'm hoping this is just because I installed the latest version of lessc, and these changes are good to incorporate. @mistakevin, @talumbau Let me know if you agree.
See https://github.com/OpenSourcePolicyCenter/webapp-public/commit/b438a927e166ce1ba29337297e4af7206f68d8f6 for the actual effective changes that fix #71.
Note I tested this locally, but hard to say if it's actually fixed due to #86.

Hotfix "from the lab" offcenter on HP - fixes #71

---

templates/taxbrain/input_form.html
webapp/apps/taxbrain/views.py

118 errors as warnings

---

webapp/apps/dynamic/views.py
webapp/apps/taxbrain/views.py

- restrict dynamic simulations to only start year of 2015

Add start years of 2016 and 2017

---

webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/tests.py

- change rounding function to only round on values >= 1.0

Resolves #160

---

webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/migrations/0016_taxsaveinputs_job_not_ready.py
webapp/apps/taxbrain/migrations/0017_auto_20160229_0159.py
webapp/apps/taxbrain/models.py
webapp/apps/taxbrain/views.py

- add 'jobs_not_ready' field to taxsaveinputs model

Only check on jobs that aren't done

---

templates/dynamic/behavior.html
templates/dynamic/dynamic_input_form.html
templates/dynamic/elasticity.html
templates/dynamic/landing.html
templates/taxbrain/input_form.html
webapp/apps/dynamic/helpers.py

Add flatblock above Get Started on TaxBrain page

---

templates/dynamic/elasticity.html
templates/dynamic/includes/params/inputs/elastic.html

I missed a couple of places where AMTR should be 1 - AMTR. These are small text changes. 
cc @talumbau @mistakevin

AMTR -> 1 - AMTR. Small text changes. 

---

webapp/apps/dynamic/helpers.py

Small text fix for gdp elast model.

wage income -> income in information i hover over text for gdp elast

---

templates/register/post-signup-register.html
webapp/apps/register/forms.py
webapp/apps/register/models.py

tweak to the mailing signup text.

beta test -> try

---

webapp/apps/dynamic/compute.py
webapp/apps/dynamic/tests/test_ogusa.py
webapp/apps/dynamic/tests/utils.py
webapp/apps/dynamic/views.py

- get start year from request
- add test to check that 2016 OGUSA sim has first_year=2016

Remove hard-coded start year for OGUSA jobs

---

webapp/apps/dynamic/compute.py
webapp/apps/taxbrain/compute.py
webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/tests/test_all.py
webapp/apps/taxbrain/tests/test_views.py
webapp/apps/taxbrain/tests/utils.py

- add Growth metadata parameters to package_up_vars

Add DROPQ_WORKER_OFFSET to round-robin over nodes

---

templates/dynamic/includes/params/inputs/dynamic.html
webapp/apps/dynamic/helpers.py
webapp/apps/dynamic/tests/test_ogusa.py
webapp/apps/dynamic/tests/test_views.py
webapp/apps/dynamic/tests/utils.py
webapp/apps/dynamic/views.py

- only appears when user is not logged in
- if we can't get an email address from the user or they leave the field
blank, raise a 403

Add email field to OGUSA input

---

webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/tests/test_all.py

- don't round to nearest integer on rates

fix packaging up rates and propagating forward

---

webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/tests/test_all.py

- Handles start year beyond end of defaults

Additional wildcard processing

---

webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/tests/test_all.py

Add Per. refund. credit and phaseout as inflatable

---

webapp/apps/dynamic/helpers.py
webapp/apps/dynamic/tests/test_ogusa.py

Add default parameter values to OGUSA email

---

webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/migrations/0021_auto_20160505_1445.py
webapp/apps/taxbrain/tests/test_all.py
webapp/apps/taxbrain/views.py

Unicode issue 232

---

templates/dynamic/behavior.html
templates/dynamic/dynamic_input_form.html
templates/dynamic/elasticity.html
templates/dynamic/elasticity_results.html
templates/dynamic/landing.html
templates/dynamic/results.html
templates/taxbrain/header.html
templates/taxbrain/input_base.html
templates/taxbrain/input_form.html

Added offset calc on click

---

static/js/taxbrain.js
staticfiles/js/taxbrain.js

Taxbrain auto-scroll on Firefox

---

webapp/apps/taxbrain/forms.py
webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/tests/test_all.py
webapp/apps/taxbrain/tests/test_views.py
webapp/apps/taxbrain/views.py

- Resolves #257
- Enhance form logic to handle wildcard entry prior to field validation

Accept wildcards on fields that validate

---

templates/taxbrain/includes/params/inputs/behavior.html
templates/taxbrain/includes/params/inputs/behavior_alone.html
webapp/apps/dynamic/migrations/0012_auto_20160616_1908.py
webapp/apps/dynamic/models.py
webapp/apps/dynamic/views.py

- Fix for viewing results of partial equilibrium simulations

BE_CG_per -> BE_cg

---

templates/dynamic/results.html
webapp/settings.py

Fix OGUSA Results page title

---

templates/taxbrain/includes/params/inputs/refundable_credit.html
templates/taxbrain/input_form.html

Hide Growth Assumptions section for now

---

templates/taxbrain/includes/params/inputs/growth.html
templates/taxbrain/includes/params/inputs/refundable_credit.html
templates/taxbrain/input_form.html

- change name to "Baseline Growth Assumptions"

Add Growth Assumptions parameters back to TaxBrain

---

templates/btax/includes/params/inputs/taxes.html
templates/btax/results.html
webapp/apps/btax/helpers.py
webapp/apps/btax/views.py

Small update to #345. Requested fixes noted in commit history. Resolves #322

Brendancol nafix ccc mods

---

.travis.yml
webapp/apps/btax/helpers.py
webapp/apps/btax/views.py

Remove the "fixup" that forced `btax_betr_entity_Switch` to True.

don't change btax_betr_entity_Switch from default

---

.travis.yml
Procfile
static/js/btax.js
static/js/filetb.js
staticfiles/js/btax.js
staticfiles/js/filetb.js
templates/taxbrain/failed.html
templates/taxbrain/includes/params/inputs/box.html
templates/taxbrain/includes/params/inputs/file.html
templates/taxbrain/includes/params/inputs/json.html
templates/taxbrain/input_base.html
templates/taxbrain/input_file.html
templates/taxbrain/input_json.html
templates/taxbrain/results.html
webapp/apps/btax/compute.py
webapp/apps/btax/views.py
webapp/apps/dynamic/views.py
webapp/apps/taxbrain/compute.py
webapp/apps/taxbrain/migrations/0032_auto_20161004_1216.py
webapp/apps/taxbrain/migrations/0033_auto_20161004_1548.py
webapp/apps/taxbrain/migrations/0034_auto_20161004_1953.py
webapp/apps/taxbrain/models.py
webapp/apps/taxbrain/tests/test_views.py
webapp/apps/taxbrain/urls.py
webapp/apps/taxbrain/views.py
webapp/settings.py

- Error messages on failure to parse JSON
- If valid JSON but unable to run microsim, present remote error on
failed job page
- Input boxes for Calculator, Growth, and Behavior
Resolves #312

JSON based input page taxbrain/json

---

templates/dynamic/landing.html
webapp/apps/dynamic/views.py

- disallow OGUSA when microsim reform is from a file

Modify dynamic choices for file-based reforms

---

templates/btax/input_form.html
templates/btax/results.html

- Resolves #367 Order of Output Tables
- Resolves #321 - hide start year input
- Resolves #366 - change CCC image for dark background

Fix CCC input and output issues

---

templates/btax/includes/params/inputs/depreciation.html
webapp/apps/btax/helpers.py
webapp/apps/btax/views.py

- use text from 'hover' notes in btax default parameters

Add hover overs to column headings on CCC

---

templates/btax/results.html

Make the METTR variable the default output.  Order output radio buttons so METTR, METR, CC, Depreciation.

reorder output variables

---

templates/btax/input_form.html
templates/taxbrain/header.html

Header on CCC input and results page fix

---

templates/btax/results.html
webapp/apps/btax/tests/test_views.py
webapp/apps/btax/views.py

- add depreciation fixup to set model params based on
selected switch in Depreciation table
- Resolves #352

Edit Parameter button on CCC

---

templates/taxbrain/includes/params/inputs/refundable_credit.html

Remove Additional additional child tax credit

---

static/js/btax.js
staticfiles/js/btax.js
templates/btax/includes/params/inputs/macro_econ.html
templates/btax/includes/params/inputs/other.html
templates/taxbrain/includes/params/inputs/payroll.html

General fixes for BTax / Taxbrain Input pages

---

requirements.txt
webapp/apps/btax/compute.py
webapp/apps/btax/helpers.py
webapp/apps/btax/views.py
webapp/apps/dynamic/compute.py
webapp/apps/dynamic/helpers.py
webapp/apps/taxbrain/compute.py
webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/models.py
webapp/apps/taxbrain/views.py

- Additional updates to support taxcalc 0.7.0

Remove dependency on dropq package

---

static/js/taxbrain-tablebuilder.js

Additional commit to change text labels.

Change text labels for Fiscal total tables

---

webapp/apps/dynamic/views.py

- Use new keys for updated Table Builder js code
- Resolves #425

Fix Partial Equilibrium results output

---

webapp/apps/dynamic/tests/test_views.py
webapp/apps/dynamic/views.py

Check for FAIL status on macro elasticity jobs

---

templates/btax/results.html
webapp/apps/btax/helpers.py
webapp/apps/btax/views.py

Fixes #422 and will simplify the creation of B-Tax results.

move logic to B-Tax for formatting its tables

---

templates/btax/input_base.html
templates/taxbrain/input_base.html

CCC and TaxBrain pages link to About page

---

templates/pages/home.html
webapp/apps/pages/views.py

Add links to gallery page.

---

templates/btax/input_form.html

Bigger CCC Logo

---

static/js/taxbrain.js

Remove edited class when reset button is pressed.

---

static/js/taxbrain.js
webapp/apps/taxbrain/views.py

Fix Edit Parameters Rendering

---

templates/pages/hello.html
templates/pages/home.html
webapp/apps/pages/urls.py
webapp/apps/pages/views.py

Embed Google Form at /hello

---

staticfiles/js/taxbrain.js

Restore taxbrain.js file.

---

templates/taxbrain/includes/params/inputs/behavior_alone.html
webapp/apps/dynamic/migrations/0013_auto_20170331_2032.py
webapp/apps/dynamic/models.py
webapp/apps/dynamic/tests/test_behavioral.py
webapp/apps/dynamic/tests/test_elasticity.py
webapp/apps/dynamic/views.py
webapp/apps/taxbrain/compute.py
webapp/apps/taxbrain/forms.py
webapp/apps/taxbrain/migrations/0047_auto_20170329_1954.py
webapp/apps/taxbrain/migrations/0048_auto_20170330_2012.py
webapp/apps/taxbrain/models.py
webapp/apps/taxbrain/tests/test_views.py

Contains code from bugfixes for #493 . Merged all outstanding PRs into this branch to fix problems with builds and testing. Will close the existing PRs.

Marketing Deploy Updates (WIP)

---

webapp/apps/taxbrain/forms.py

Turn Boolean Fields into Checkboxes

---

webapp/apps/taxbrain/helpers.py

avg -> total in tables. 

---

templates/taxbrain/default_input.html
templates/taxbrain/input_form.html
webapp/apps/taxbrain/forms.py
webapp/apps/taxbrain/helpers.py

Form Field Fixes (WIP)

---

templates/btax/input_base.html
templates/pages/home.html
templates/taxbrain/input_base.html

Drip Tracking for Webapp

---

webapp/apps/taxbrain/migrations/0053_auto_20170725_2141.py
webapp/apps/taxbrain/models.py
webapp/apps/taxbrain/tests/test_models.py

Fix Issue with Character Limit

---

conda-requirements.txt

Revert to Version 0.9.0

---

webapp/apps/taxbrain/helpers.py

Remove lines that were lower-casing the titles.

---

webapp/apps/taxbrain/compute.py
webapp/apps/taxbrain/views.py

This PR addresses bugs in PR #641 as discussed in [PR #637](https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/637#issuecomment-330242830).  
@brittainhard is this the fix that you had in mind?

Gui input processing bug fixes

---

webapp/apps/taxbrain/views.py

Show reform contents when assump file is not uploaded

---

webapp/apps/taxbrain/helpers.py
webapp/apps/taxbrain/views.py

Revert switches from 1/0 to True/False in model

---

webapp/settings.py

This PR manually changes the PolicyBrain version from 1.0.2 to 1.0.3

Update webapp version to 1.0.3

---

webapp/apps/taxbrain/tests/test_views.py
webapp/apps/taxbrain/views.py
webapp/apps/test_assets/test_reform.py

This PR handles the case where a file was uploaded with errors.

Add file input warning/error handling logic

---

RELEASES.md

This updates RELEASES.md for version 1.1.0.

Add PRs to RELEASES.md for version 1.1.0

---

RELEASES.md

This updates RELEASES.md for PR #675

Update RELEASES.md for PR #675

---

RELEASES.md
webapp/settings.py

This PR involves no change in logic.  The version is updated in `settings.py`, and the 1.1.1 section is added to `RELEASES.md`.

Update hardcoded version to 1.1.1 and RELEASES.md

---

RELEASES.md

If you contributed to PB 1.2.0, take a look at the README.md and make sure you agree with how your contribution is described.  Feel free to propose a different description or propose that a contribution should be moved to another category (i.e. PR 123 really should be a minor change and not a bugfix).
cc @GoFroggyRun @hayleefay @MattHJensen

Update RELEASES.md for 1.2.0

---

RELEASES.md
webapp/settings.py

Feel free to chime in on how the PR's were assigned to bug fix or minor change, wording, etc.
@GoFroggyRun @MattHJensen

Update RELEASES.md and hardcoded version for 1.2.1

---

static/js/taxbrain-tablebuilder.js
static/js/vendor/DataTables/datatables.js
staticfiles/js/taxbrain-tablebuilder.js
staticfiles/js/vendor/DataTables/datatables.js

Fix buttons disappear after fiscal tables being re-rendered

---

conda-requirements.txt
webapp/apps/taxbrain/migrations/0059_auto_20171216_2123.py
webapp/apps/taxbrain/models.py

Upgrades PolicyBrain to TC 0.14.1.  
@martinholmer @MattHJensen Do you agree with doing this upgrade?  Do you think there will be another TC release in the coming days that I should wait for?  Also, are there any presets that you would like to add?

Upgrade to TC 0.14.1

---

webapp/apps/taxbrain/views.py

Removes extra "Total" labels

---

RELEASES.md
webapp/settings.py

Updates RELEASES.md and hardcoded version for PolicyBrain 1.2.2.

Update to PolicyBrain 1.2.2 --> 1.3.0

---

RELEASES.md
templates/taxbrain/input_form.html
webapp/settings.py

Reverts OpenSourcePolicyCenter/PolicyBrain#835 and adds #834

Revert #835 and add #834

---

RELEASES.md
templates/taxbrain/input_form.html
webapp/settings.py

Remove presets and add notice/explanation

---

distributed/api/endpoints.py

Bug fix for #914
