OpenSourcePolicyCenter/PolicyBrain

- webapp/apps/taxbrain/helpers.py
- If this feature is turned on (currently defaults to off), TaxBrain
will check if the version of the remote workers is the same as the
local version of taxcalc, and raise an error if there is not a match
> adds option of enforcing a version check

- templates/taxbrain/results.html
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/urls.py
- webapp/apps/taxbrain/views.py
- Adds new view 'taxbrain/edit/{id}. We go back to the database
to get the model parameters and then populate the input screen
based on that. This avoids any issues with storing input info
in the session, which we previously had a problem with.
> Fix 'Edit Parameters' button on results page

- templates/taxbrain/includes/params/inputs/other_taxes.html
- templates/taxbrain/includes/params/inputs/soc.html
- templates/taxbrain/input_form.html
- webapp/apps/taxbrain/helpers.py
- Remove Additional Medicare from the other taxes section
- Remove the max taxable earnings for Social Security from the Social
Security and Medicare section
- Rename the Social Security and Medicare section to Social Security
Taxability
> Removing Medicare sections

- webapp/apps/taxbrain/migrations/0011_taxsaveinputs_job_ids.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/views.py
- Job IDs for processing jobs are moved from the session to being stored
on the model. This allows the user to run multiple jobs in different
tabs in the browser. W/o this, the different jobs in different browser
tabs would conflict and all tabs would get the same completed job.
This fix will cause more queries to the database, but it's the most
correct way to handle processing jobs
> Remove job IDs from session - store on model

- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/tests.py
With release of `taxcalc 0.6`, we have floating point values for our parameters. When these values are CPI-inflated in time, we choose to round them to the nearest dollar when displaying them on TaxBrain.
> Round all parameter values to the nearest dollar

- templates/dynamic/behavior.html
- templates/dynamic/dynamic_input_form.html
- templates/dynamic/elasticity.html
- templates/dynamic/landing.html
- webapp/apps/dynamic/helpers.py
- rename the partial equilibrium simulation.
- change "start macro simulation" buttons to "start dynamic simulation"
- note that the GDP elasticity is wrt 1-AMTR instead of AMTR after https://github.com/OpenSourcePolicyCenter/dropQ/pull/47
- update the default GDP macro elasticity rate from 0.54 to 0.0 per #174 
- update the information 'i' text for the gdp macro elasticity to reflect the change in the previous point. 
cc @talumbau @mistakevin
> Minor edits

- webapp/apps/taxbrain/compute.py
- webapp/apps/taxbrain/tests/test_views.py
- Fixes a bug that would crash the app if attempting to submit to a node
that is misbehaving. We only look at the contents of the repsonse if
we get a 200 from the worker node
> Only read JSON response after checking status code

- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/tests/test_views.py
- Grab any set CPI flags from the model we are editing and then
populate the attrs of the widget of the associated CPI flag field
and set to the value that comes from the model
> Fix CPI flag switches on edited microsims

- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/tests/test_all.py
- Sends proper parameter name (with '_' prefix) to
indexing_rates_for_update method to get the proper rates for
propagating value forward in time
- resolves #224
> Fix _SS_earnings_c to index by wage rate

- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/tests/test_all.py
- indexing was incorrect in plugging in expanded defaults
- add test for multiple wildcards in a multi-valued parameter
> Fix multi-value params with multiple wildcards

- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/tests/test_all.py
- floating point 0 asserts to False. Correct assertion here is making
sure that the empty string or None is not passed
Resolves #259 and #261
> Fix incorrect assert in propagate_user_list

- webapp/apps/dynamic/tests/test_behavioral.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/compute.py
- Resolves #206
- Partial equilibrium simulations based on microsim runs that involved
wildcard entries for reform parameters were not getting the proper
reform parameters. Now they are correctly processed and sent off for
processing
> Fix: wildcard entries propagate to part. eq. sims

- templates/pages/embed.html
- templates/pages/widget.html
- webapp/apps/pages/urls.py
- webapp/apps/pages/views.py
This PR adds an additional endpoint for accessing widgets (e.g. `tax reform explorer`).
An individual widget is accessed by id using the following url syntax:
`/widgets/<widget_id>/`
> added widget page

- webapp/apps/taxbrain/compute.py
- webapp/apps/taxbrain/tests/test_views.py
> Quick calculations don't increment node counter

- webapp/apps/btax/compute.py
- webapp/apps/btax/tests/test_views.py
- webapp/apps/taxbrain/compute.py
- For BTax workloads, we don't need to increment the counter
that keeps track of of offset in the worker node pool
- depends on #319
> Add flag to increment worker nodes counter

- templates/taxbrain/includes/params/inputs/file.html
- templates/taxbrain/input_file.html
- templates/taxbrain/results.html
- webapp/apps/taxbrain/views.py
- monospace font for reform file text
- white space respected in text from file
- More descriptive/appropriate text on file-based reform input page
> Better formating for file-based reuslts pages

- templates/taxbrain/failed.html
- webapp/apps/taxbrain/views.py
- Errors from file-based TaxBrain runs are reported in monospace font
and with white space respected.
- resolves #370
> Improved error reporting on file-based runs

- webapp/apps/btax/helpers.py
This PR updates the references used to pull text from the `btax_defaults.json` file for the hover tooltips in the CCC depreciation parameters input table.
> update tooltip references

- templates/btax/results.html
- webapp/apps/btax/helpers.py
This fixes issues related to row ordering on /ccc results tables and gets rid of the extra footer info.
Here is the new industry look:
This shows the minor headings "Durable goods" and "Nondurable goods" inside "Manufacturing" section:
And here's the fixed footer:
> Fix /ccc row ordering issues: 385, 386, 387, 388

- static/js/taxbrain-tablebuilder.js
- staticfiles/js/taxbrain-tablebuilder.js
Looks like there was a check for a `col.show` on the `FiscalTable` which I removed and now all years are displayed.
> removed check for "show" property on fiscal table columns #419

- templates/btax/results.html
Ensure the "All Investments" row is at the bottom of each of /ccc results tables.  Must work with [B-Tax PR 120](https://github.com/open-source-economics/B-Tax/pull/120)
> add All Investments row at the bottom of /ccc results tables

- templates/taxbrain/results.html
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/compute.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/views.py
- A file-based reform could have behavioral parameters. If this is the
case, you should not be able to launch a dynamic simulation.
- Adds a modal pop-up if user clicks Link to Dyn. Sims on results page
for file based reform that includes behavior parameters.
- Behavior is unchanged if file based reform contains no behavioral
components
- Depends on change to worker node
- Resolves #431
> Only allow links to dynamic simulations on non-behavior run

- templates/taxbrain/includes/params/inputs/file.html
- templates/taxbrain/results.html
- webapp/apps/dynamic/tests/utils.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/migrations/0041_auto_20170126_0317.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/tests/test_all.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
- One file input for the reform, one for assumptions
- Migrate data model so JSON input has reform_text, assumption_text
- Handle error cases of 0 or only 1 reform file provided
- Instead of passing arbitrary string text in POST, provide dictionary
of the form { "reform": string, "assumptions": string}
- Necessary change for taxcalc 0.7.4
- Update some hard-coded test data since values in taxcalc changed
> Refactor taxbrain/file to handle two file inputs

- webapp/apps/btax/compute.py
- webapp/apps/btax/views.py
* Btax results were being given to a compute.py dropq_get_results function that was expecting non-B-Tax keys (taxbrain - taxcalc specific keys)
* This PR fixes that endpoint - I think the broken endpoint on results was causing our hanging behavior on heroku recently with /ccc
> fix btax result endpoint so not expecting taxcalc keys

- webapp/apps/taxbrain/helpers.py
As discussed in [#534](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/534#issuecomment-296374906), the terminology for the diagnostic tables and the difference tables are different. 
The is old title name:
This is the title name proposed in this PR:
All "Per" are changed to "By" so that the diagnostic tables and the difference tables have consistent title names. 
@brittainhard @MattHJensen Could you review?
> Change Title Terminology for Tables

- static/js/taxbrain-tablebuilder.js
- staticfiles/js/taxbrain-tablebuilder.js
In [#534](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/534#issuecomment-296374906), @MattHJensen suggested:
>TOTAL LIABILITIES TABLES: Should not include the year in the table name. Currently the "Change" and "Current Law" tables include the start year in parenthesis.
as well as 
>TOTAL LIABILITIES CHANGE TABLE: TOTAL LIABILITIES CHANGE BY CALENDAR YEAR (2017) should be TOTAL LIABILITIES BY CALENDAR YEAR (CHANGE)
This PR addresses these two concerns. After the fix, the table will look like the following:
For Current Law:
For Reform:
And for Difference:
Could you review? @MattHJensen @brittainhard
> Remove Year "( 2017 )" in the Total Liability Table

- deploy/taxbrain_server/celery_tasks.py
- webapp/apps/taxbrain/compute.py
- webapp/apps/taxbrain/tests/test_compute.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_reform.py
@PeterDSteinberg @martinholmer @MattHJensen @hdoupe
I was unable to add a unit test that could help us solve the problem with this file, mainly because it would require saving `puf.csv.gz`. I was, however, able to make a small script that duplicates the behavior that is causing the problem.
```
import json
import celery
import pandas as pd
import taxcalc
from deploy.taxbrain_server.celery_tasks import dropq_task
behavior_params = {u'growdiff_response': {}, u'consumption': {}, u'behavior': {}, u'growdiff_baseline': {}}
user_mods = {u'2019': {u'_SS_Earnings_c': [500000], u'_ALD_InvInc_ec_rt': [0.2]}, u'2020': {u'_SS_Earnings_c': [600000], u'_II_em_cpi': True}, u'2018': {u'_SS_Earnings_c': [400000], u'_II_em_cpi': False, u'_II_em': [8000]}}
puf = pd.read_csv("puf.csv.gz", compression='gzip') …
```
> File Upload Fixes

- deploy/fab/dropq_environment.yml
- requirements.txt
- templates/btax/not_ready.html
- templates/btax/results.html
- webapp/apps/btax/bubble_plot/bubble_plot_tabs.py
- webapp/apps/btax/bubble_plot/controls_callback_script.py
- webapp/apps/btax/bubble_plot/styles.py
- webapp/apps/btax/views.py
- webapp/apps/dynamic/helpers.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/views.py
This PR includes a bokeh bubble plot that will appear on the results page of the ccc.
> Bubble plot visualization

- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/compute.py
- webapp/apps/taxbrain/views.py
> Fix btax backend bug caused by PR #641

- webapp/apps/taxbrain/views.py
@GoFroggyRun this is a dirty prototype but it works. It just loops through the tables of the existing data structure and adds up their values, then creates a new column. The front-end is handling it well, no changes need to be made there. I haven't tested this solution thoroughly, and the code could be improved. This is a good basis for the feature I think. My output from a reform looks like this:
It's adding the column AFTER the table has already been saved in the database. I think this can also be done after before the data is saved in the database. I don't think that will cause issues with backwards compatibility since the javascript table is just accepting arbitrary data as long as its in the right format.
@martinholmer @hdoupe your input on this would he helpful I think.
> Add summary row for table

- static/js/taxbrain-tablebuilder.js
- staticfiles/js/taxbrain-tablebuilder.js
Per requests in #545, the fiscal year table (a.k.a Total Liabilities table) doesn't have appropriate labels for three cases. More explicitly, when clicking on either Current Law or Reform, then row label indicates "xxxxx Liability Change", which is not appropriate under those two cases. 
This PR drops word "Change" from row labels in those cases. And three tables (reform, current law, and change) will look like the following:
@brittainhard Could you review?
cc @martinholmer @MattHJensen
> Modify row labels for fiscal table

- static/js/taxbrain-tablebuilder.js
- static/js/vendor/DataTables/datatables.js
- staticfiles/js/taxbrain-tablebuilder.js
- staticfiles/js/vendor/DataTables/datatables.js
- webapp/apps/constants.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/views.py
Per request in #620, one of the buttons in "build table" option is mislabeled. This PR renames "diagnostic" as "distribution" for this particular button, as well as for the tooltips in the code base. 
After this PR, the build table panel would look like the following:
@brittainhard could you please review?
cc @martinholmer @MattHJensen
> Rename "Diagnostic Table" to "Distribution Table"

- templates/pages/about.html
- templates/pages/home.html
This PR tries to close issue #584.
1. CCC has been added to "OUR PRODUCTS":
2. Twitter link has been added. (FB and LinkedIn links are still pending)
3. The "APP" link on the bottom of home page has been fixed, which directs to TaxBrain page. 
@brittainhard Please review. 
cc @MattHJensen
> Web Page Clean Up

- static/js/vendor/DataTables/datatables.js
- staticfiles/js/vendor/DataTables/datatables.js
Per requests in #545, the title name for liability table is not right when user exports the table via "Print" button. 
Beforehand, the title name was "Welcome to TaxBrain". After this PR, the title name, when being printed, would be more informative, that is also consistent with the title name on the result page. 
The new page generated from the "Print" button for liability table will look like:
@brittainhard Could you please review?
cc @MattHJensen
> Change title name for liability table

- static/js/taxbrain-tablebuilder.js
- staticfiles/js/taxbrain-tablebuilder.js
This PR fixes the bug reported in #644. 
Before this PR, when payroll tax is ON and income tax is OFF, the difference table will show combined taxes; when payroll tax is ON and income tax is ON, the difference table will show payroll taxes. Both cases are incorrect. 
The fix in this PR assigns proper data to each button so that:
```
Pay_taxes is ON    Inc_taxes is ON    ===>  Combined taxes are shown
Pay_taxes is ON    Inc_taxes is OFF   ===>  Payroll taxes are shown
Pay_taxes is OFF   Inc_taxes is ON    ===>  Income taxes are shown
Pay_taxes is OFF   Inc_taxes is OFF   ===>  Nothing is shown
```
This PR also changes the two buttons' names from "Payroll" and "Income" to "Payroll Tax" and "Income Tax", as requested in #644 .
However, turning OFF the two buttons, namely "Payroll Tax" and …
> Fix Payroll Tax + Income Tax buttons on difference table

- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/compute.py
- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/views.py
Applies GUI processing logic from #641 to the macroeconomic elasticity model.
> Elastic submit bugfix

- deploy/setup.py
- webapp/apps/taxbrain/views.py
> Refactor submit_reform for quick-calc submission case

- deploy/taxbrain_server/celery_tasks.py
- templates/taxbrain/results.html
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/compute.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/views.py
> Fix dynamic simulation button logic for file upload

- conda-requirements.txt
This PR pins Bokeh to version 0.12.7.  See PR #687 and issue #686 for further discussion.
> Pin Bokeh to 0.12.7

- webapp/apps/taxbrain/helpers.py
- webapp/apps/test_assets/test_assumptions.py
- webapp/apps/test_assets/test_param_formatters.py
- webapp/apps/test_assets/test_reform.py
This PR adds unit tests for functions introduced in PR #641 and related PRs.  Tests were added for the following functions:
1. [`taxbrain.helpers.get_default_policy_param_name`](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/helpers.py#L260)--Two minor bugs were discovered while adding tests and they will be fixed in subsequent commits
2. [`taxbrain.helpers.to_json_reform`](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/helpers.py#L290)
3. [`taxbrain.helpers.parse_errors_warnings`](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/views.py#L152)
4. [`taxbrain.views.read_json_reform`](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/master/webapp/apps/taxbrain/views …
> Unit test parameter formatters 

- static/js/taxbrain-tablebuilder.js
- static/js/vendor/DataTables/Buttons-1.1.0/js/buttons.flash.js
- static/js/vendor/DataTables/Buttons-1.1.0/js/buttons.html5.js
- static/js/vendor/DataTables/Buttons-1.1.0/js/dataTables.buttons.js
- static/js/vendor/DataTables/datatables.js
- staticfiles/js/taxbrain-tablebuilder.js
- staticfiles/js/vendor/DataTables/Buttons-1.1.0/js/buttons.flash.js
- staticfiles/js/vendor/DataTables/Buttons-1.1.0/js/buttons.html5.js
- staticfiles/js/vendor/DataTables/Buttons-1.1.0/js/dataTables.buttons.js
- staticfiles/js/vendor/DataTables/datatables.js
Closes #678. The new toolbox have three options:
Excel-related code lines are removed
> Remove "Excel" button for both tables

- templates/taxbrain/results.html
- webapp/apps/taxbrain/templatetags/results.py
This PR closes #500. A filter, `nbsp`, is added to disable stripping white spaces. Also modified title name as suggested in #500 by @MattHJensen.
Before this PR, the file upload section looks like: 
The new file preview looks like:
where the uploaded file looks like:
```
{
"policy": {
"_SS_Earnings_c": {"2018": [400000], "2019": [500000], "2020": [600000], "2021": [600000], "2022": [600000], "2023": [600000], "2024": [600000]},
"_II_em": {"2018": [8000]},
"_II_em_cpi": {"2018": false,
"2020": true},
"_ALD_InvInc_ec_rt": {"2019": [0.20]}
}
}
```
> Enhance file upload preview

- templates/taxbrain/input_form.html
Closes #704. This adds a preset for the Brown-Khanna Gain Act of 2017.  This is based off of @martinholmer and @MattHJensen's work in PR open-source-economics/Tax-Calculator#1555.  The notes file is based off of @martinholmer's work in open-source-economics/Tax-Calculator#1607.  
This PR follows the admittedly sub-optimal process of keeping the reform notes in a Google doc.  In the near future, a better solution needs to be found.
> Add Brown-Khanna Gain Act of 2017 preset

- templates/dynamic/elasticity.html
- templates/dynamic/includes/params/inputs/elastic.html
For some reason, #684 was accidentally reverted while auto merging. This PR retained the reverted changes. 
@hdoupe could you take a look and merge.
> Fix reverted Macro page changes 

- templates/pages/home.html
- templates/pages/home_content.html
This PR closes #727. 
The Policy Brain app is not able to find `news.ospc.org` without supplying a full hyper link, for the reason that the blog (news) page is hosted somewhere else outside the app. 
There's no way for me to test on my local (the previous link works just fine on local as well as on test app). I used console to substitute HTML elements on [ospc.org](https://www.ospc.org/) by hard-coding, and it seems that, after making the following changes, the website has no problem accessing `news.ospc.org`.
@hdoupe @MattHJensen
> Fix "news.ospc.org" link bug

- webapp/apps/btax/bubble_plot/bubble_plot_tabs.py
- webapp/apps/btax/bubble_plot/controls_callback_script.py
This PR fixes issue #728 by correcting the initial loading values of the assets shown in the hover-over and dynamically updating the title of the plots and the x-axis label.
> Labels and titles dynamically update and initial loading bug fixed

- templates/taxbrain/default_input.html
This PR collapse in all fields temporarily @hdoupe.
> Collapse in all fields temporarily 

- templates/taxbrain/input_form.html
This PR removes a no longer needed UBI conditional statement.  It looks like this was added to keep the UBI parameter from showing up in the GUI input page.  However, we want the UBI params to show up now.  Further, it doesn't look like it actually did anything.  See #746
> Remove UBI exclude statement

- deploy/taxbrain_server/celery_tasks.py
- webapp/apps/dynamic/views.py
This PR cleans up the changes added by #738. 
1. Year keys in user_mods dictionaries ('policy', 'growdiff_response', 'behavior', 'consumption', 'growdiff_baseline') are converted to int in `celery_tasks.py`
2. Temporary table logic is added for partial equilibrium sim results.
> Post 738 dynamic sim clean up

- webapp/apps/taxbrain/views.py
Resolves #750 
50 seconds was chosen since the webapp takes about 40 seconds to run one year of static analysis.  This should be a safe amount of time to allow for one year's calculation.
> Change job_proc_time from 30 to 50 seconds

- webapp/apps/taxbrain/helpers.py
> Fix table label order

- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
This PR simply changes the parameter formatting.  For unknown reasons, sometimes parameters get swapped from 0 to `False` or from 1 to `True`.  Using the `benefit_switch_fixup` function ensures uniform formatting of this type of parameter:
> Make sure ID_AmountCap_Switch param is submitted as 1/0

- webapp/apps/taxbrain/views.py
@GoFroggyRun's comment in PR #760 led me to this solution.  In particular, @GoFroggyRun said:
> In particular, before this PR, some code in input_base.html reads:
> ```
>   {% if input_type == "file" %}
>   <script src="{% static 'js/filetb.js' %}"></script>
>   {% else %}
>   <script src="{% static 'js/taxbrain.js' %}"></script>
>   {% endif %}
> ```
> The if loop here, however, will always fall into the else clause, and thus causing #760.
In PR #641, I removed this from the context.  Sometimes I do things that are both extremely frustrating and highly amusing.  This happens to be one of them.  Check out this [comment](https://github.com/OpenSourcePolicyCenter/PolicyBrain/commit/85183a88bc593361eb1a1a240b01a8d070d06d3a#diff-8bfe9696ea1ed6a7d52dfb5455a2f47bR341):
> Add input_type back to context

- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_reform.py
This PR begins to resolve #769 part 3 and resolves #769 part 4.
1. Adds a more informative description for what a warning and error message look like:
2. Includes offending parameter in the message.  This was not needed in the GUI messages since it was obvious that the message applied to the parameter whose box it was displayed under.  As @martinholmer pointed out, it is not so obvious when the messages are displayed on the file input page.
> Update warning/error messages and description

- webapp/apps/btax/forms.py
- webapp/apps/btax/helpers.py
- webapp/apps/btax/views.py
- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/migrations/0060_auto_20171219_2153.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/tests/test_helpers.py
- webapp/apps/taxbrain/tests/test_views.py
Resolves #765.  This PR treats `DependentCredit_before_CTC` as an integer instead of a boolean parameter which allows the user to very the parameter's value over time.
EDIT:
Old behavior:
New behavior:
> Convert DependentCredit_before_CTC from bool to int

- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/tests/test_helpers.py
- webapp/apps/taxbrain/tests/test_views.py
This PR converts 1/0 values back to boolean variables and serializes them.  PolicyBrain reads the default GUI parameter values from Tax-Calculator's [`default_data`](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters.py#L24) function.  This [line in parameters.py](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters.py#L438) converts boolean parameters from true/false to 1/0.  This treatment is currently only applied to `DependentCredit_before_CTC` but will be applied to the other comma separated boolean variables as they are added.
Before this PR, the default parameter value for `DependentCredit_before_CTC` was shown as:
Behavior introduced by this PR shows:
> Convert default values for boolean parameters from 1/0 to "True"/"False"

- templates/taxbrain/input_form.html
- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/tests/test_helpers.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_reform.py
This PR adds the reverse operator discussed in issue #763. 
Basic rules as described in this [comment](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/763#issuecomment-353669184) in #763 :
> I think we should impose some strict rules on how this symbol can be used so that we can keep everything simple.
> 
> 1. It can only be used at the beginning of the string.
> 2. It can only send a parameter back one year (this rule could be relaxed fairly easily)
> 
> For example, if you set the start year as 2018 and the cpi_offset parameter to "<,-0.0025", then this sets the cpi_offset to -0.0025 in 2017.
> Add reverse operator

- webapp/apps/taxbrain/views.py
This PR preserves the start year after a file is uploaded and warnings are shown.  Prior to this PR, the start year was wiped out after the warnings/errors were shown for a file upload.
> Saves start year after warnings are shown for file upload

- webapp/apps/taxbrain/helpers.py
This PR improves comments for the function that maps TaxBrain styled names to Tax-Calculator styled names.
> Add examples for get_default_policy_param_name

- .travis.yml
- do_nothing.txt
We've been getting the following error when travis does a PolicyBrain build after a PR is merged or a new version is released:
https://travis-ci.org/OpenSourcePolicyCenter/PolicyBrain/builds/327422754?utm_source=github_status&utm_medium=notification
This stems from travis-ci/travis-ci#4704.  The patch was provided in this comment: https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
I tested the patch by opening the following PR on my PolicyBrain fork: hdoupe/PolicyBrain#5
> .travis.yml update to fix build errors

- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_param_formatters.py
- webapp/apps/test_assets/test_reform.py
This PR refactors the warning/error parsing logic. This reduces duplicated code and puts the warning/error parsing logic under test.
cc @codekansas
> Refactor warning/error parsing

- templates/pages/gallery.html
Replaces https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/803 using a branch.
> Fix "Vizualization" typo in Gallery

- webapp/apps/btax/bubble_plot/bubble_plot_tabs.py
This PR resolves issue #764 and adds a legend to the bubble plot shown after running the cost of capital calculator.
I opted to add a second Bokeh figure to act as the legend because Bokeh's legend feature does not allow you to use circle of different sizes and it let me add the "Asset Amount" title easily.
cc @hdoupe @jdebacker
> Add Legend to Bubble Plot

- .gitignore
- deploy/install_taxbrain_server.sh
Explanation:
- `.DS_Store` - Useless file created by Mac file browser
- `.egg-info` - Created when doing pip install
- `staticfiles` - Migrated staticfiles, should probably be ignored
- `pip install -e .` - Safer / more consistent version of `python setup.py develop`
I talked to @hdoupe about my regular schedule now so expect commits around this time MWF/Sat/Sun.
> Small changes to .gitignore and install script

- templates/dynamic/behavior.html
- templates/dynamic/dynamic_input_form.html
- templates/dynamic/elasticity.html
- templates/dynamic/elasticity_results.html
- templates/dynamic/landing.html
- templates/dynamic/results.html
- templates/pages/apps.html
- templates/taxbrain/header.html
- templates/taxbrain/input_file.html
- templates/taxbrain/input_form.html
Fix for https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/815
Hmm... Turns out there's a lot of repeated things that are kind of a mess to maintain. I was thinking that a good way to unify the "text-heavy" parts of this project would be to use something like Jekyll, so that the texts of like the "about" parts could be written first in Markdown then built to HTML, which would be much cleaner than just writing everything in HTML (as it currently stands). For example, disclaimers and stuff that is used frequently throughout multiple apps could be written once, so that if they have to be updated somewhere down the line it is cleaner / safer than running some complicated grep. For example, you can put peoples' emails in a yaml file so that they can be updated / referenced more …
> Changed all instances of TJ Alumbaugh's email address

- webapp/apps/taxbrain/behaviors.py
- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/tests/test_models.py
- webapp/apps/taxbrain/views.py
In some last minute testing, I pointed my local app to a back up of the production database and uncovered two backwards compatibility bugs that sprung up when you visited the edit parameter pages for older runs:
- CPI parameters were stored as boolean values not as strings.
- For really old runs, the start year value is null.
> Resolve edit-parameter page backwards compatibility bugs

- .travis.yml
- RELEASES.md
- conda-requirements.txt
- deploy/fab/dropq_environment.yml
- deploy/fab/redeploy.py
- deploy/fab/reset_server.sh
- deploy/install_taxbrain_server.sh
- deploy/requirements.txt
- webapp/settings.py
Last night, I was unable to reset the node environments because it was unable to install `btax`. In this PR, I refactored the install scripts so that all of the OSPC packages are installed with conda instead of some confusing mix of cloned github repos and pip installations. 
All packages are installing correctly now. The only problem is that they are in a different location relative to the PUF file. Thus, if you run [TaxBrain on the test app](http://ospc-taxes7.herokuapp.com/taxbrain/1558/), you get:
taxcalc traceback:
or on [CCC you get:](http://ospc-taxes7.herokuapp.com/ccc/175/)
btax traceback:
```
Traceback (most recent call last):
File "/home/ubuntu/miniconda2/envs/aei_dropq/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
R = retval = fun(*args, **kwargs) …
```
> Update deployment process to use conda/pip instead of cloning github repos

- RELEASES.md
- conda-requirements.txt
- webapp/apps/dynamic/models.py
- webapp/apps/taxbrain/behaviors.py
- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/param_formatters.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_param_formatters.py
- webapp/settings.py
Specifying a parameter for the standard deduction caused a warning on the widow parameter. This PR removes errors that are not allowed on un-displayed parameters.
> Remove errors for un-displayed parameters and save input data for warning/error message page

- RELEASES.md
- webapp/apps/dynamic/forms.py
- webapp/apps/taxbrain/forms.py
This PR refactors the TaxBrain form logic so that the page form data is re-generated each time a page is loaded. In order to save user input data as a JSON object instead of columns (see #822), we need to dynamically add fields to the `ModelForm` subclass. We must do this because the `ModelForm` class expects there to be a mapping from the database fields to the form fields. But, what we have is a mapping from form fields to items in a JSON object which is stored in the database more or less as a blob of data. Thus, the form fields were dynamically created from the keys in the blob of data. This was done by directly modifying the `fields` attribute of an instance of (subclass of?) `django.ModelForms`. 
The previous logic created all of the form data once--on start up--in an inner class …
> Generate new form data for each page load

- RELEASES.md
- webapp/apps/taxbrain/forms.py
- webapp/settings.py
The column labels were removed in PR #822. This PR adds them back:
> Add column ID's back to PolicyBrain

- RELEASES.md
- deploy/taxbrain_server/celery_tasks.py
- deploy/taxbrain_server/flask_server.py
- webapp/apps/dynamic/forms.py
- webapp/apps/dynamic/models.py
- webapp/apps/dynamic/tests/test_behavioral.py
- webapp/apps/dynamic/tests/test_elasticity.py
- webapp/apps/dynamic/tests/test_models.py
- webapp/apps/dynamic/tests/utils.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/behaviors.py
- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/tests/test_models.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_models.py
- webapp/apps/test_assets/utils.py
- webapp/settings.py
This PR gray's out fields depending on the data source selection. For example, if you select the data source "CPS", then you get the following display:
Note that these fields cannot be edited.
cc @andersonfrailey @GoFroggyRun
> Gray out fields based on data-source selection

- RELEASES.md
- webapp/apps/dynamic/tests/test_behavioral.py
- webapp/apps/dynamic/views.py
The start year was not correctly retrieved from the request parameter data. This bug was likely introduced in #822 as part of the effort to upgrade to Django 1.9. This PR fixes this issue. 
[EDIT] The issue was that we quit checking for the start year parameter in the `GET` data. You can see that it was [there initially](https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/162/files#diff-ad4af3b555fda282262b117143191048R227). However, since the "blame" was not preserved very well, I'm not sure where this was dropped.
> Pass start year to dynamic behavioral

- .travis.yml
- RELEASES.md
- requirements.txt
- static/js/filetb.js
- templates/taxbrain/input_file.html
- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/submit_data.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/utils.py
This PR does three things:
1. Adds the data source to the file input page using the same approach as the GUI input page
2. Refactors the reform submission to the worker nodes so that the post data is stored in a `namedtuple` instead of a dictionary. This replaces a combination of dictionaries and tuples with the class-like `namedtuple`. In my opinion, this enhances the readability of the code. I'm interested in others thoughts on this though.
3. In order to utilize pytest's `parameterize` functionality in class methods, the class has to inherit from `object`. Since many methods needed to be tested with both `data_source` arguments ('PUF' and 'CPS') and there wasn't much benefit from using `django.TestCase`, I made this change. For now, this only applies to the TaxBrain static model views …
> Adds data source to file input page, refactors reform submission, and improves tests

- templates/taxbrain/not_ready.html
To avoid "About a few seconds remaining"
Reported in https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/850.
> Change "About _ remaining" to "Estimated time remaining: _"

- templates/btax/input_form.html
This PR fixes a link that will be broken with the merge of [B-Tax PR #207](https://github.com/open-source-economics/B-Tax/pull/207).
It also removes Ben Gardner's name as a core maintainer.  I think this is safe to do since he's been off the project for more than 18 months.
> Update link to CCC guide

- templates/taxbrain/input_form.html
Add a link to the data description doc to TaxBrain. Full text is:
>TaxBrain now offers users two data options: CPS and PUF. Both datasets contain tax unit level data, but they do not have all of the same variables. As a result, you will not be able to change some policy parameters, depending on which dataset you choose. A more detailed breakdown of the differences between the file can be found here.
cc @hdoupe @MattHJensen
> Add link to data document

- RELEASES.md
- distributed/Dockerfile.celery
- distributed/Dockerfile.flask
- distributed/docker-compose.yml
- webapp/apps/taxbrain/views.py
This PR bumps up the job processing time form 30 seconds to 90 seconds. See #861 for more information on this. 
This PR also tags the docker images. This allows us to know the exact state of the workers for each version of PolicyBrain (which I am pretty pumped about).
> Updates job time and adds version to docker files

- RELEASES.md
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
> Extend tests and fix warning/error handling regression

- templates/dynamic/elasticity_results.html
- templates/taxbrain/includes/results/elasticity_table.html
I removed all non-functional buttons for the elasticity result page for the moment. I also plan to permanently get rid of the "Save As" drop-down whose options don't make much sense in my opinion.
I re-organized the div element a bit so that the table can be properly accessed, and was able to have the "Print" button semi-working. Here's how the page would look like:
A new window would pop-out with the same content in the table that allows you to print/save. I plan to polish the table layout a bit which would complete this button.
> Restore "Print" button for elasticity output page

- templates/taxbrain/input_form.html
This PR changes "Data Source" to "Principal Data Source" and adds an extra sentence to the datasets description.
cc @MattHJensen
> Change Data Related Text

- webapp/apps/constants.py
This PR changes the order of the Data Source dropdown in TaxBrain so that `PUF` is the first option.
> Change Dropdown Order

- RELEASES.md
- templates/btax/not_avail.html
- templates/taxbrain/not_avail.html
- webapp/apps/btax/tests/test_views.py
- webapp/apps/btax/views.py
- webapp/apps/dynamic/tests/test_behavioral.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
This PR adds renders the `not_avail.html` page (see #874) when an error is thrown while rendering simulation results.
For TaxBrain:
For CCC:
> Back-end for not_avail.html page

- RELEASES.md
- webapp/apps/btax/tests/test_views.py
- webapp/apps/btax/views.py
- webapp/apps/dynamic/models.py
- webapp/apps/dynamic/tests/test_behavioral.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
For some older runs, the start year was not saved. So, when you try to go to the edit parameters page from the `not_avail.html` page and don't have a start year, the link looks like: `/taxbrain/edit/100/?start_year=None` and you get the following error:
The production database has about 700 out of 30000 runs with out a start year and all of them were created in 2014 or 2015. This PR uses the current default start year as the start year value. This may not be the most accurate. Perhaps, using the year from the creation date is more accurate. But, that solution adds more complexity to the code for a small sample of the runs. Also, I feel like using the current start year is the most transparent option. I'm open to other ideas though.
> Use current default start year if start year was not saved

- templates/btax/header.html
- templates/btax/not_avail.html
- templates/btax/not_ready.html
- templates/btax/results.html
- templates/taxbrain/header.html
Per discussion in #874, this PR separates the header template so that btax and taxbrain would use their own `header.html.` This makes future maintenance easier when content in either file needs to be updated. 
I noticed that there are some other btax HTMLs using files in taxbrain's directory. For instances [here](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/2fa70f4dd6f1d003208b4345e99bcc41befeff7a/templates/btax/includes/params/inputs/macro_econ.html#L1) and [here](https://github.com/OpenSourcePolicyCenter/PolicyBrain/blob/2fa70f4dd6f1d003208b4345e99bcc41befeff7a/templates/btax/includes/params/inputs/macro_econ.html#L26-L27). In fact `taxbrain /input_form_section.html` and `taxbrain/includes/params/inputs/param.html` are extensively used for files within the directory …
> Create respective `header.html` files for btax and taxbrain

- webapp/apps/btax/models.py
- webapp/apps/btax/views.py
- webapp/apps/dynamic/models.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/behaviors.py
- webapp/apps/taxbrain/compute.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_models.py
New AWS instances were set up for PB 1.5.0. This PR fixes a case where the previous hostnames were pinged to check on an old, failed result. Instead of pinging the no longer used hostnames, we render a job failed page.
> Check hostnames to make sure they are current before pinging them

- webapp/apps/constants.py
- webapp/apps/taxbrain/views.py
> Add formatting to warn/error messge banner

- RELEASES.md
- webapp/apps/dynamic/views.py
This PR makes two bug-fixes:
- Shows error message on dynamic behavioral page as implemented in #891 
- Adds `growmodel` keyword for args to Tax-Calculator elasticity endpoint
> Quick dynamic app parameter fixes

- templates/btax/results.html
- webapp/apps/btax/bubble_plot/bubble_plot_tabs.py
- webapp/apps/btax/views.py
Bokeh visualization working on 0.12.9 and CDNs for widgets now dynamic, rather than being pinned to a specific version.
Issue #687
> Adding dynamic CDNs for the widgets

- README.md
I noticed while setting up a local installation of PolicyBrain that these steps are definitely needed (to install prerequisite packages TaxBrain and B-Tax).
> Add necessary steps to setup instructions

- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/views.py
Various suggestions for changes to the TaxBrain views file, mainly to meet PEP8 guidelines and for general cleanup. Also, some list comprehensions are changed to generator expressions. I'm looking forward to feedback about whether these are too many or too few changes for this purpose.
> Various code style improvements, mainly to TaxBrain views

- static/js/vendor/DataTables/datatables.js
Addresses #885. It may be that the minified file has to be updated too, although I'm not sure if it's actually being used.
> Make title row of generated CSV file have correct number of columns

- webapp/apps/taxbrain/views.py
Addressing second part of #883, i.e. removing warnings/errors for running the TaxBrain model with current tax policy / no reforms.
> Allow for running the model without reforms

- webapp/apps/dynamic/tests/test_views.py
- webapp/apps/dynamic/views.py
Add default parameter handling for macro elasticity simulation. Follow-up to #883 and #905: currently, running the macro elasticity model without inputting any data results in not even a UI error, but an uncaught server error in converting an empty string to a float. This adds default handling in a general way. However, it does make the assumption that there is only one column/value per input; this was already implied in the previous code, and I believe that should be okay for this model, but please let me know if it is not.
> Add default parameter handling for macro elasticity simulation

- webapp/apps/btax/models.py
- webapp/apps/btax/views.py
- webapp/apps/dynamic/models.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/models.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_models.py
- webapp/apps/test_assets/utils.py
Change naive datetime objects to timezone-aware ones. This has the advantage of fixing 200+ warnings when running the tests, and everything seems to work with this change.
> Change datetime objects to timezone-aware ones

- webapp/apps/dynamic/forms.py
- webapp/apps/dynamic/tests/test_views.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/tests/test_views.py
Implement parameter validation for input_fields, both for TaxBrain and for the partial equilibrium model.
> Implement parameter validation for input_fields

- RELEASES.md
- templates/taxbrain/results.html
- webapp/apps/dynamic/views.py
This PR:
- removes references to `dynamic_input_parameters`
- saves foreign key with `taxbrain_model.json_text.save()` (who knew all the ways you had to save a django relation?)
- use `set_fields` and `to_json` to create `raw_assumption_text` field if it is not there
@lucassz can you review this?
> Cleans up input parameter save and display logic for dynamic app

- DOCKER.md
- distributed/api/endpoints.py
Load Redis client from existing environment variable instead of hardcoding an unchangeable hostname for it. Necessary for #913 in an auxiliary way, and seems like a good practice. It's not totally clear to me what the distinction between `CELERY_BROKER_URL` and `CELERY_RESULT_BACKEND` (which we set to the same value in practice) is, so do let me know if it should be the other one.
> Load Redis client from existing environment variable

- webapp/apps/conftest.py
- webapp/apps/constants.py
- webapp/apps/dynamic/tests/test_behavioral.py
- webapp/apps/dynamic/tests/test_elasticity.py
- webapp/apps/dynamic/tests/test_models.py
- webapp/apps/dynamic/views.py
- webapp/apps/taxbrain/submit_data.py
- webapp/apps/taxbrain/tests/test_models.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/taxbrain/views.py
- webapp/apps/test_assets/test_models.py
See #894: 
> The high level parameter submission logic is housed primarily in submit_reform. This is a complex function and does not have any unit tests. There are a fairly high number of paths that data can take through this function: File or GUI? Full calculation or quick calculation? Errors or no errors? If errors, were they detected in PolicyBrain or the upstream project? If errors, what type of errors and has the user seen them? On top of that, this function produces about 20 pieces of data.
> 
> The aim for this first PR is to:
> 1.  Move submit_reform into its own module. This makes the views.py module more pure in the sense that its functions map directly to web pages (i.e. a TaxBrain inputs page, an outputs page, an edit parameters page, etc.). This also modularizes the …
>  Beginning steps for refactoring high level submission logic (retry of #894)

- webapp/apps/taxbrain/forms.py
- webapp/apps/taxbrain/helpers.py
- webapp/apps/taxbrain/param_formatters.py
- webapp/apps/taxbrain/submit_data.py
- webapp/apps/taxbrain/tests/test_helpers.py
- webapp/apps/taxbrain/tests/test_views.py
- webapp/apps/test_assets/test_param_formatters.py
`ast.literal_eval` throws a syntax error in Python 3 when passed a string like `"01"`. In Python 2, `ast.literal_eval` parses this string to `1`. The behavior has been changed to return the original, unparsed value if an exception is thrown. Errors such as this should be caught by the initial input validation logic. The only reason that this occurred is that bad data got through the initial form validation.
Note that there was a bug where the wrong variable was returned and a `NameError` was thrown. This has been fixed.
While working on the issue above, I noticed that the input value validation logic needed some serious work. I spent some time trying to get the `pyparser` library to work as expected, but I was unsuccessful. Thus, I wrote an `is_safe` function that tests:
- how long is the …
> In Python 3, '01' causes a syntax error when evaled via ast.literal_eval
